### PR TITLE
bikeshed: do not default md-warning if md-status is LS-PR

### LINKED ISSUE #55: WHATWG sets a warning in our default Bikeshed boilerplate, which PR Preview overrides
In https://github.com/tabatkins/bikeshed/blob/master/bikeshed/boilerplate/whatwg/computed-metadata-LS-PR.include we have set the `warning` metadata to `custom` for all WHATWG spec builds with the LS-PR status. This makes it use the warning at https://github.com/tabatkins/bikeshed/blob/master/bikeshed/boilerplate/whatwg/warning-custom.include.

However, when deploying using PR Preview, this gets overridden. See, for example, https://whatpr.org/storage/86.html. This is due to https://github.com/tobie/pr-preview/blob/a38138ef02f65d8829a2c01c5a7195fa7b4ea941/lib/models/config.js#L44-L47.

I'm unsure of the best solution for working around this conflict. There's no way to know precisely that the default metadata for a given org/status has set `md-warning`, so I understand why you're relying on the incoming config instead.

Maybe we could hard-code an exception for `LS-PR` statuses, on the reasoning that they probably have their own custom warning anyway by virtue of being a special status dedicated for PR previews?

### PR DESCRIPTION
**Pull request by annevk**
Closes #55.

### CODE REVIEW

File: lib/models/config.js [hunk 1]
```diff
@@ -41,8 +41,10 @@ module.exports.addDefault = function(config) {
             config.params.isPreview = true;
         }
     } else if (type == "bikeshed") {
-        if (!config.params || !("md-warning" in config.params)) {
+        if (!config.params) {
             config.params = config.params || {};
+        }
+        if (!("md-warning" in config.params) && config.params["md-status"] !== "LS-PR") {
```
Comment (tobie) [inline lib/models/config.js:47]:
```suggestion
        if (!("md-warning" in config.params) && config.params["md-status"] !== "LS-PR") {
            // See https://github.com/tobie/pr-preview/issues/55 for for why LS-PR is special-cased.
```

File: lib/models/config.js [hunk 2]
```diff
@@ -41,8 +41,11 @@ module.exports.addDefault = function(config) {
...
+            // See https://github.com/tobie/pr-preview/issues/55 for for why LS-PR is special-cased.
```
Comment (tobie) [inline lib/models/config.js:48]:
```suggestion
            // See https://github.com/tobie/pr-preview/issues/55 for why LS-PR is special-cased.
```

**Comment by tobie** [comment]
Fix has been deployed.
